# Generated by Django 4.1.5 on 2023-02-08 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_rename_razorpay_order_id_payment_stripe_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Cancel', 'Cancel'), ('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Packed', 'Packed'), ('Accepted', 'Accepted'), ('On The Way', 'On The Way')], default='Pending', max_length=50),
        ),
    ]
